typedef sequence<VertInf> VertexList;
typedef sequence<ConnRef> ConnRefSet;
typedef sequence<VertInf> VertexSet;

[Prefix="Avoid::"]
interface HyperedgeNewAndDeletedObjects {
  attribute JunctionRef[] newJunctions;
  attribute unsigned long numberOfNewJunctions;
  attribute JunctionRef[] deletedJunctions;
  attribute unsigned long numberOfDeletedJunctions;
  attribute ConnRef[] newConnectors;
  attribute unsigned long numberOfNewConnectors;
  attribute ConnRef[] deletedConnectors;
  attribute unsigned long numberOfDeletedConnectors;
  attribute ConnRef[] changedConnectors;
  attribute unsigned long numberOfChangedConnectors;
};

[Prefix="Avoid::"]
interface HyperedgeRerouter {
  void HyperedgeRerouter();

  // TODO: fix, cannot be overloaded
  // unsigned long registerHyperedgeForReroutingViaVector(ConnEnd[] terminals);
  unsigned long registerHyperedgeForRerouting(JunctionRef junction);

  unsigned long count();

  [Value] HyperedgeNewAndDeletedObjects newAndDeletedObjects(unsigned long index);
};
